### ISSUE TITLE
Better Enhanced Steam API progress/error exposure

### ISSUE THREAD

**Issue by stuartpb** [jshackles/Enhanced_Steam#1081]
It'd be nice if, when the Steam Summer Sale starts and everybody pounds api.enhancedsteam.com into the dirt, the extension would recognize the incoming 520 errors and insert a message above the price where IsThereAnyDeal information normally goes that says "Enhanced Steam is experiencing abnormal load right now. For additional pricing information, please try again later."

**Comment by jshackles** [comment]
That's not a bad idea!  :+1: 

There is the loading bar at the top that should turn into a red square if it fails to retrieve data, so at least there is some indication, but I agree it might be best to explicitly let the user know that that request failed rather than simply not altering the page (making it look like the extension might not be working).

**Comment by stuartpb** [comment]
Ohh, *that's* what that red square is. See, that doesn't work as a feedback mechanism, because unless you're watching that corner of the screen from the beginning of the page load - and you infer, in the absence of any labels (other than the tooltip) that the progress bar in the corner is for Enhanced Steam API data - and you're watching at the *precise moment* that the progress bar transitions directly to the collapsed red square, there's *no indication* what it's meant to indicate (and even if you *do* catch all that, it's still a pretty big leap without any sort of identification).

In most use cases, where the user has scrolled down to read the page's content after it finishes loading, they never see the progress indicator in the header at *all*, and when they *do* scroll up and see it after completion, the green-circle-versus-red-square indicator could be interpreted as:

- A "busy" or "offline" Friends status indicator
- An indicator that Steam itself is functioning (including something to do with the desktop client's status)
- A button / UI affordance for some niche Enhanced Steam beta feature that they haven't worked with yet, that's using a plain red/green square/circle as temporary placeholder art until someone contributes a proper icon
- A beacon GIF for analytics that someone just didn't make properly transparent
- What team they're on in some kind of hellish rerun of the Summer 2014 metagame (ESPECIALLY if they were on red/green team)
- VAC status
- A debugging artifact that's snuck into the page's HTML due to some developer option they inadvertently enabled

The proper UX for Enhanced Steam's shims, as I see it, would be to copy the design of the Steam Community's functionality: insert them into the page as soon as possible with a "Loading..." animation as their content, then swap the final data in once it's ready, or say "Looks like we had a problem. Reload?" if something goes wrong.

**Comment by JoiNNN** [comment]
Since then, the progress indicator when something fails was made easier to understand, and some details are provided with which requests failed when hovering the indicator. The option to add custom and more user friendly messages instead of a plain URL was also added. We can add an option to toggle between showing plain URLs and user friendly messages if needed.

**Comment by seeeeew** [comment]
I think some messages should be replaced with more user friendly ones (like "ES servers are probably down, please try again later") while most should be as developer friendly as possible, because they are of no use for the user anyway.
