### ISSUE TITLE
Enhanced_Steam as userjs

### ISSUE THREAD

**Issue by lollox** [jshackles/Enhanced_Steam#1149]
As in title, I'd like to have an userjs version of Enhanced Steam

**Comment by jshackles** [comment]
Then you should... try to make one?  The reason Enhanced Steam evolved from originally being a greasemonkey script to a full-blown extension was that extensions support APIs such as storage that can easily be used to cache data client-side and that they can be pre-packaged with images and scripts that are loaded with the extension rather than being constantly redownloaded from a web server.  Additionally the make things like options easy to configure and sync storage allows these options to sync across multiple devices.  As far as I'm aware, a flat script version of Enhanced Steam would inherently be missing a large number of it's features.

But the software is open source and freely available.  As long as you follow the licensing requirements of the GPL, you or anyone else is free to try to build such a version.

**Comment by JoiNNN** [comment]
Can be closed.
