### ISSUE TITLE
Please readd home page customisation

### ISSUE THREAD

**Issue by chrcoluk** [jshackles/Enhanced_Steam#1190]
I lost my much tidied up home page, seems a bit off to remove a feature just because a minor amount of users had crashes.

**Comment by jshackles** [comment]
Rest assured, this is being worked on.  The feature was removed because users were experiencing crashes, but I'd also like to point out that after the home page update the feature was also completely broken and unusable and needed to be re-written anyway.

Hopefully I'll have something put together in the next couple of days.

**Comment by chrcoluk** [comment]
ahh ok so its just temporary, thanks.

are the settings still intact for home page customisations?

**Comment by JoiNNN** [comment]
This can be closed.
