### ISSUE TITLE
Logged out every 10-15 minutes, all cart gone

### ISSUE THREAD

**Issue by kokizzu** [jshackles/Enhanced_Steam#1240]
Don't know why but when using this extension, every 10-15 minutes, i'm logged out from steam and all cart gone (i have to readd everything from beginnning)

**Comment by JoiNNN** [comment]
AFAIK there is no code in ES that can log you out, if you suspect there is something conflicting causing the logouts try disabling ES for  while (an hour, a day) and see if the issue persists. Also since this happened around winter holidays it might've been a problem on Valve's side.
This can be closed for now.
