### ISSUE TITLE
[Conflict] FairSteam extension videos appear blank

### ISSUE THREAD

**Issue by gab** [jshackles/Enhanced_Steam#1344]
It seems Enhanced Steam conflicts with this very nice extension https://github.com/EvergreenPotato/FairSteam, i.e. when clicking its video thumbnails all you get is a blank space.

It would be nice if a communication channel was established between both projects to ensure compatibility.

**Comment by JoiNNN** [comment]
Although some conflicts are expected to occur with other extensions (especially with FairSteam since it directly replaces Valve's scripts in order to implement it's features in a more seamless way) in Chrome at least, there are no issues on my side, everything works as expected. So please, if you could provide more details: browser, extensions (and their version) pages the error occurs on etc.

**Comment by gab** [comment]
It'd be best to contact directly the FairSteam dev as he seemed convinced that this problem is due to a conflict with Enhanced Steam.

Browser: Chrome 58. I have a lot of extensions installed including uBlock Origin, but I ran some tests in a new profile with fewer extensions and it didn't seem to help.

For me it randomly started working again, but I'll try and isolate/reproduce the problem when it comes back and document my steps this time.

**Comment by JoiNNN** [comment]
AFAIK this has been fixed on FairSteam's side. The issue can be closed.
