### ISSUE TITLE
[Bug]? "Current Lowest Price" of trading cards in Badge page is not working for some currencies.

### ISSUE THREAD

**Issue by Z56B29A2** [jshackles/Enhanced_Steam#1510]
As stated in title.
Not sure if it is a bug or just a function that haven't been enabled for some currencies. 

The "Current Lowest Price" in Badge page always shows 0 no matter what the actual price is. This happened on HKD TWD and CNY, yet on USD GBP and EUR everything seems to work as intended.

I haven't test other currencies yet, so it could happened on other currencies too.

![2017-12-16_214202](https://user-images.githubusercontent.com/34614351/34076305-c9a87d24-e2d9-11e7-998a-148490ec3fde.png)

Cheers,

**Comment by jshackles** [comment]
The price conversion on this feature is done server-side presently but that is causing issues with the currencies and the fact that Valve is supporting over 30 currencies now.  This feature needs to be re-written so that the value requested from the server is always in USD and the conversion happens client-side (since the client is already caching the conversion rate table anyway).

This should be fixed in the next release.

**Comment by Z56B29A2** [comment]
@jshackles Good to know! Thanks for your quick reply and effort on this great project.
 (๑•̀ㅂ•́)و✧
