### ISSUE TITLE
[Suggestion] Add Option to Tag/Highlight/Hide Games That Have Been Marked as "Not Interested."

### ISSUE THREAD

**Issue by allthegoodnamesaretaken** [jshackles/Enhanced_Steam#619]
This would allow people to more easily ignore games that they are already on record as not wanting.

**Comment by tomerbarkan** [comment]
I'd love to see this too. When I search steam, I have no way of telling if this is a game I've already reviewed and decided it's not interested. I wish they were marked like wishlist. Follow marking would also be nice.

**Comment by JoiNNN** [comment]
For search you already have the option while searching to hide games previously marked as "Not Interested". There is no highlighting feature for those tho...

**Comment by allthegoodnamesaretaken** [comment]
There is a check box for the option, but it doesn't appear to work for me. That might be because I have +8,800 games marked as not interested, but still.

**Comment by tomerbarkan** [comment]
I can't even see this option. Where is it?

**Comment by allthegoodnamesaretaken** [comment]
In the search browser, in the hide pane under "Items not discounted."

**Comment by JoiNNN** [comment]
@allthegoodnamesaretaken it works for me, I'm looking into whether high number of apps would cause it to not work properly.
@tomerbarkan  
![aadd](https://cloud.githubusercontent.com/assets/3322834/15100196/819cb352-156b-11e6-91b2-a26cc31395ff.png)

**Comment by allthegoodnamesaretaken** [comment]
Much appreciated.

**Comment by tomerbarkan** [comment]
I see it now, and it works. Too bad it's not there when browsing top sellers, new releases, etc...
This feature matters more when browsing and not when searching by text for specific titles.

**Comment by Black3ird** [comment]
Can't believe this 2014 thread is still overlooked. The Not Interested data is already there and known by the ES since you can hide them in search page only. It is also in http://store.steampowered.com/dynamicstore/userdata/ by rgIgnoredApps which most likely the ES gets the data from. And all the mechanics for handling such is already done for wishlisting.

What is left is just copy pasting the wishlisting code and edit the parts that take rgWishlist data to take rgIgnoredApps data instead. Since it is not reinventing the code, I guess it could be done in short time if it is wanted to do so.

Please consider this much needed functionality since Steam users generate extra Internet traffic for both Steam and ES, constantly revisiting the titles that they are not interested but didn't know beforehand until they loaded the page.

**Comment by tomerbarkan** [comment]
Awesome thanks!
However, one small change I'd suggest - if a game is wishlist + not interested, wishlist should take precendent (it usually means you don't want to see it in the homepage anymore, but you do want it)

**Comment by allthegoodnamesaretaken** [comment]
Thanks for listening, it works great! One small thing is that the "Hide if marked not interested" and the Not Interested Tags/highlights don't keep up with the infinite search scroll feature.
