### ISSUE TITLE
Suggestion: sorting out game by %

### ISSUE THREAD

**Issue by 11Thor11** [jshackles/Enhanced_Steam#656]
I would like to see a way to sort out games by the discount % if there is a way, if not then thats fine.

**Comment by Invisiblessed** [comment]
This is going to be an absurd bump, but I may well do this instead of creating another post. +1 to this suggestion - if this could be implemented before the Summer sale, that would be fantastic. Catching those big software packages that still hit around $50 even when discounted heavily would be great.

**Comment by JoiNNN** [comment]
If this was intended for wishlists then it's been done.

**Comment by jshackles** [comment]
This has been implemented in the wishlist but the suggestion for this I personally get most often refers to the search page.  Unfortunately there isn't a way to accomplish this outside of pre-caching all of the results server side and letting users browse a separate page.  This is similar to what SteamDB does for their "sales" page which makes a lot more sense than trying to shoehorn the feature into Steam itself by overriding the results on the search page.
