### ISSUE TITLE
[Feature] Additional sorting options for /games/?tab=all

### ISSUE THREAD

**Issue by ladeedaa** [jshackles/Enhanced_Steam#704]
In my case, that would be: http://steamcommunity.com/id/tripleslash/games/?tab=all  
This page lets you filter by "installed games", which is very useful, and would be even more so if you could sort by Steam and metacritic rating on top of that, not to mention filtering by genres and/or tags.  
Any chance of something like this?

**Comment by jshackles** [comment]
Unfortunately, information about each game (such as genre/steam rating/metacritic/etc) isn't exposed anywhere on this page.  For Enhanced Steam to be able to do this, it would need to pull this data from another source for each game, such as the game's store page.

The problem is that some people, such as myself, have over 2,000+ games on this list, meaning it would generate, at a minimum, 1 XHR request per game.  This could slow (or even freeze) the user's browser, and would cause a considerable strain on Steam's servers.

If Steam eventually decides to list this info somewhere on this page, I would be happy to include this as a feature.
