### ISSUE TITLE
[Suggestion]I have a small script which can add ANY custom pic for your steam background

### ISSUE THREAD

**Issue by ds375394022** [jshackles/Enhanced_Steam#743]
Sorry for my bad English
Just a suggestion, maybe your group can develop your script of 'add background from steam game library' to 'add ANY custom pic for your steam background'
Only need to record the picture outside the chain of address for the ES users, I think it will not take up a lot of server resources
Here is my script, it can be used by tampermonkey, you can edit or do anything with it, never mind. I like your works, and I hope you will add this function in ES :)

**Comment by CorruptComputer** [comment]
Why not PR this? You shouldn't make an issue for a feature suggestion, and then GIVE all the code needed.

**Comment by jshackles** [comment]
One of the key points of our "add any background to your Steam profile" feature is that other users are able to see the background image you select.  Allowing users to select any image they want to their Steam profile background opens Enhanced Steam up to a huge potential liability issue, because someone may choose to use an offensive, copyright infringing, or pornographic image which would then be visible to others.  We currently do not have the manpower which would be needed to moderate such a feature.
