### ISSUE TITLE
[Suggestion] Show ratings in wishlist

### ISSUE THREAD

**Issue by seeeeew** [jshackles/Enhanced_Steam#889]
Showing ratings in the wishlist would help sorting out large wishlists.

**Comment by thomas-ashcraft** [comment]
By the way, it would be nice to display the rating on the game collections pages. Because some packages are not worth buying due to crap games they full of. And every time you need to open page of each game in package and check out it rating.

For example:
http://store.steampowered.com/sub/18406/
or
http://store.steampowered.com/sub/51460/

**Comment by seeeeew** [comment]
Might be a good suggestion, but it belongs in an own issue, not this one. ;)

**Comment by JoiNNN** [comment]
Added. Can be closed.
