### ISSUE TITLE
Fail to Load Steam Market Data for H1Z1 Items

### ISSUE THREAD

**Issue by Bonsai99** [jshackles/Enhanced_Steam#984]
Same issue with both H1Z1: King of the Hill and H1Z1: Just Survive inventories.

Endlessly tries to load and shows "Error loading enhanced steam data" at the top of the page.

Screenshot - http://i.imgur.com/2zMLoO4.png

Example Inventory - http://steamcommunity.com/id/TrashDump/inventory/

**Comment by JoiNNN** [comment]
Seems to work just fine for me at the moment. Please note that with the major these past few days many things were slow or even broken on Steam's side. If the issue persists let let us know.

**Comment by Bonsai99** [comment]
Enhanced Steam loads all market data properly for seemingly every other inventory. Cleared the Enhanced Steam cache as well as tested this on another computer, same issue.

Did some further looking around and It looks like the Market Hash name isn't being set properly on H1Z1 items, they are just undefined.

Here are screenshots showing a working request and a bad request.

http://imgur.com/a/5rbg0

Chrome Version 49.0.2623.110 m (64-bit)
Enhanced Steam v8.3

**Comment by JoiNNN** [comment]
Found out what the issue was and submitted a fix. Thanks for reporting.

**Comment by Codingale** [comment]
@JoiNNN has something recently changed as I can't seem to get the listings for cards.

Noticed that it's sending XHR's to `http://steamcommunity.com/market/priceoverview/?currency=1&appid=753&market_hash_name=undefined` Pretty sure undefined isn't intended.

**Comment by JoiNNN** [comment]
@Codingale can you please provide more details? Did it happen while viewing you inventory, what card or item.

**Comment by Codingale** [comment]
Did some more digging, turns out the Opera store has an outdated version, I had to install it manually from the chrome instructions and it's a large change.

Opera version was 7.1.1, latest is 9.1.

Probably need @jshackles to update it.  (also @JoiNNN posted literally 1 minute before I thought to check to see if it's the latest version)

**Comment by jshackles** [comment]
I've sent the latest versions to Opera's team, but they have unfortunately declined to publish them.  As the version that's posted there is so out of date, it's probably time to "officially" drop Opera support or change the website's instructions so that it instructs users to download the Chrome version.  It currently just says:

> Due to Opera's manual review process, this version might be out of date. Most Opera users can also download the Chrome version of Enhanced Steam.
