### ISSUE TITLE
Suggestion Chat

### ISSUE THREAD

**Issue by Royalgamer06** [jshackles/Enhanced_Steam#989]
Add this if you want:
https://greasyfork.org/en/scripts/18690-steam-community-chat-dropdown
You have my permission :+1:

**Comment by JoiNNN** [comment]
I like that, nice idea. I'll look into getting it to open the chat window for web version too.

**Comment by Royalgamer06** [comment]
What do you mean with "open the chat window for web version too"? It already does that.

**Comment by JoiNNN** [comment]
For me it doesn't, it is predicted to happen if you look at the code and there is a supposed fix for it but it doesn't work, for me at least.
```
function LaunchWebChat( params )
{
	var winChat = window.open( '', 'SteamWebChat', 'height=790,width=1015,resize=yes,scrollbars=yes' );
	if ( !winChat )
	{
		// popup blocked - this sometimes happens when chat is initiated from the store.  just roll with it.
		return;
	}

	if ( winChat.location ==  'about:blank' )
	{
		// created a new window, set the url
		if ( params )
			SetValueLocalStorage( 'rgChatStartupParam', V_ToJSON( params ) );

		winChat.location = 'https://steamcommunity.com//chat/';
	}
	else
	{
		if ( params )
			winChat.OnWebchatLaunchURL( params );
	}
	winChat.focus();
}
```

**Comment by Royalgamer06** [comment]
So you mean to say that ES's web chat is broken? TBH, I'm not 100% following you.

**Comment by JoiNNN** [comment]
Here, when clicking the button to send a message via the Web Chat friends' chat window as seen in the screenshot should already be open, however that doesn't happen unless you are doing it while browsing the community over HTTPS. Go to a friends' profile via **http**://steamcommunity.com/ and click the button then do it again from **https**://steamcommunity.com/ and see the bug.
![chrome_2016-04-11_20-39-54](https://cloud.githubusercontent.com/assets/3322834/14438326/d07e4d74-0025-11e6-94ac-00e9484dd5ba.png)

**Comment by seeeeew** [comment]
@JoiNNN: For me it works both with HTTP and HTTPS. Which version of Chrome are you using? (Mine is 49.0.2623.112.)

Also, keep in mind that you should never check for a localized message! Instead of `jQuery('div.profile_header_actions > a > span').text() == 'Send a Message'` you could use `jQuery("div.profile_header_actions > a[href*=LaunchWebChat]").length > 0`.

**Comment by JoiNNN** [comment]
@seeeeew I've expressed myself wrong about what the issue is. I've edited my previous post.

**Comment by Royalgamer06** [comment]
@JoiNNN You are right about one thing, I forgot to include https matching in my userscript:
// @include      http://steamcommunity.com/profiles/*
// @include      http://steamcommunity.com/id/*
is now
// @include      *://steamcommunity.com/profiles/*
// @include      *://steamcommunity.com/id/*

**Comment by JoiNNN** [comment]
Still that's not what the issue is @Royalgamer06 , I noticed that and took are of it. Is about the chat input (marked by a red square in the screenshot in my previous post) that won't be there when the chat pop-up opens originating from a HTTP page.

[Here is a gist](https://gist.github.com/JoiNNN/2175260f39802058d3b0116e926d2269) with your code modified to fix the issue I'm describing if you still haven't figured what I'm talking about, and sorry for confusing everybody :smile:

**Comment by JoiNNN** [comment]
Added. Can be closed.

**Comment by Royalgamer06** [comment]
Is it me, or doesn't this work anymore? There is no dropdown anymore.

**Comment by Royalgamer06** [comment]
It seems even my old script doesn't work anymore. Steam probably changed something.
